<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title><?=__('大航海')?> App Framework</title>
    <style type="text/css">
        body {width:480px;}
        *{margin:0;padding:0}
    </style>
</head>
<body>
    <iframe name="ifr_head" id="ifr_head" src="/index/user" style="height: 132px; width: 480px;" frameborder="0" scrolling="no"></iframe>
    <iframe name="ifr_main" id="ifr_main" src="<?=$bodyUrl?>" style="height: 1000px; width: 480px; margin-top:-3px;" frameborder="0" scrolling="yes"></iframe>
</body>
</html>