<div class="content port_bg">
    <div class="cont_top">
        <div id="port_name"><?=$portInfo['name']?></div>
        <div id="port_time"><?=$YEAR?>&nbsp;<?=$SEASON?></div>
    </div>
    <div class="notice_mission">
        <a href="#" class="notice_icon"><span class="remind_notice"></span></a>
        <a href="#" class="mission_icon"><span class="remind_mission"></span></a>
    </div>
    <a href="/map/depart/?port_to=random" class="wharf_into"></a>
    <a href="/battle/history" class="exchange_into"></a>
    <a href="/_test/temp/refresh-top" class="governor_into"></a>
    <a href="#" class="shipyard_into"></a>
    <a href="/tavern" class="tavern_into"></a>
</div>