<div id="<?=$side?>_ship_<?=$ship['ship_id']?>" ship_name="<?=$ship['ship_name']?>" init_hp="<?=$ship['hp']?>" img_standby="/img/<?=$ship['img_path_standby']?>" img_hit="/img/<?=$ship['img_path_hit']?>" img_wreck="/img/<?=$ship['img_path_wreck']?>">
    <p class="ship_img">
        <img src="/img/<?=$ship['img_path_standby']?>" />
    </p>
    <p class="ship_effect"></p>
    <span class="ship_blood blood_1">
        <span></span>
    </span>
</div>