<div class="content war_list">
    <dl>
        <? if ($logList): ?>
            <? foreach ($logList as $log): ?>
                <dd>
                    <div><?=$log['result_msg']?></div>
                    <div class="button" onclick="location.href='/battle/replay/?id=<?=$log['id']?>'"><?=__('回放')?></div>

                    <div class="button" onclick="location.href='/battle/battle/?enemy_uid=<?=$log['enemy_uid']?>'">
                        <? if ($log['attacker_uid'] == $user['uid']): ?>
                            <?=__('再战')?>
                        <? else: ?>
                            <?=__('反击')?>
                        <? endif; ?>
                    </div>
                </dd>
            <? endforeach; ?>
        <? else: ?>
            <dd style="height: 400px;"><?=__('没有战斗历史记录')?></dd>
        <? endif; ?>
    </dl>
</div>